### ISSUE TITLE
Unable to publish Runbook from Azure Automation Extension.

### ISSUE THREAD

**Issue by bzabber** [microsoft/vscode-azureAutomation#23]
Does this occur consistently? 
Repro steps:

1.
2.

Action: automation.publishRunbook
Error type: Error
Error Message: Request failed with status code 401

Version: 1.1.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by c-s-cott** [comment]
I got the same error trying to "Save as Draft"

Action: automation.saveAsDraft
Error type: Error
Error Message: Request failed with status code 401


Version: 1.1.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by Kapilhk** [comment]
Hi @bzabber , @c-s-cott,
Thanks for bringing this up. This is mainly due to the fact that Authorization token expires due to longer time frame between the login/extension launch and the attempt to publish Draft version.

While we attempt to fix it, Please use the following simple workaround:

ctrl+shift+P (to reach to command pallette) -> "Azure: Sign out"
ctrl + shift + P -> "Azure: Sign In" 

This will refresh the access

**Comment by Shruti-MS** [comment]
@bzabber ,  @c-s-cott  This issue has been resolved in beta version: can be installed as pre-release from marketplace. Do share feedback on marketplace or reopen issue if problem persists. The beta version be pushed as default by next week.
