### ISSUE TITLE
Azure Automation "Publish Runbook" fails

### ISSUE THREAD

**Issue by peterbud** [microsoft/vscode-azureAutomation#28]
Does this occur consistently?  YES
Repro steps:

1. Go to Azure Automation pane in VS Code
2. Select a runbook which has been edited
3. Rigth click, then "Publish Runbook"
4. Error appears

Action: automation.publishRunbook
Error type: Error
Error Message: Request failed with status code 401

Interestingly Fetch does work

Version: 1.1.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.1
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by Shruti-MS** [comment]
@peterbud this error occurs due to expiration of authentication token to perform publish action. This occurs when extension kept inactive for some time after login.

We are working to fix the issue. As a simple workaround until we fix the issue, you can refresh token by clicking on other automation account in your subs and then performing the publish action in desired automation account.
This will allow you to publish the runbook.
